name = "gleeunit"
version = "1.2.0"
licences = ["Apache-2.0"]
description = "Gleam bindings to Erlang's EUnit test framework"
repository = { type = "github", user = "lpil", repo = "gleeunit" }
links = [{ title = "Sponsor", href = "https://github.com/sponsors/lpil" }]
gleam = ">= 0.33.0"

[javascript.deno]
allow_read = ["gleam.toml", "test", "build"]

[dependencies]
gleam_stdlib = ">= 0.33.0 and < 2.0.0"
