name = "gleeunit"
version = "1.8.0"
licences = ["Apache-2.0"]
description = "A simple test runner for Gleam, using EUnit on Erlang"
repository = { type = "github", user = "lpil", repo = "gleeunit" }
links = [{ title = "Sponsor", href = "https://github.com/sponsors/lpil" }]
gleam = ">= 1.11.0"

[javascript.deno]
allow_read = ["gleam.toml", "test", "build"]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"

[dev-dependencies]
testhelper = { "path" = "./testhelper" }
